In [25]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD
import h5py

In [3]:
x_train =np.array([[0, 0],[0,1],[1,0],[1,1]])
y_train =np.array([[0],[1],[1],[0]])


In [7]:
model = Sequential()
num_neurons = 10
model.add(Dense(num_neurons, input_dim=2))
model.add(Activation('tanh'))
model.add(Dense(1))
model.add(Activation('sigmoid'))
model.summary()
#Some quick math: 10 neurons, each with two
#weights (one for each value in the input vector), and one weight for the bias gives you
#30 weights to learn.
#10*2+10

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 10)                30        
                                                                 
 activation_6 (Activation)   (None, 10)                0         
                                                                 
 dense_7 (Dense)             (None, 1)                 11        
                                                                 
 activation_7 (Activation)   (None, 1)                 0         
                                                                 
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [8]:
sgd = SGD(lr=0.1)
model.compile(loss='binary_crossentropy', optimizer=sgd,
metrics=['accuracy'])

/usr/local/lib/python3.10/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [9]:
model.predict(x_train)

1/1 [==============================] - 0s 394ms/step


array([[0.5       ],
       [0.4526389 ],
       [0.57300496],
       [0.5296691 ]], dtype=float32)

In [10]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 0.6992 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 13ms/step - loss: 0.6988 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 12ms/step - loss: 0.6984 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 13ms/step - loss: 0.6979 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 13ms/step - loss: 0.6975 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 15ms/step - loss: 0.6971 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 13ms/step - loss: 0.6966 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 18ms/step - loss: 0.6962 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 14ms/step - loss: 0.6958 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 10ms/step - loss: 0.6953 - accuracy: 0.5000
Epoch 11/100
1/1 [===

In [24]:
pre=model.predict(x_train>0.5)
pre

1/1 [==============================] - 0s 22ms/step


array([[0.44703123],
       [0.5151696 ],
       [0.54058903],
       [0.5178386 ]], dtype=float32)

In [23]:
class_predicted = y_train[np.argmax(pre)]
class_predicted

array([1])

In [26]:
model_structure = model.to_json()
with open("basic_model.json", "w") as json_file:
  json_file.write(model_structure)
model.save_weights("basic_weights.h5")